### ISSUE TITLE
Seeking Assistance on MPU9250 DMP Implementation

### ISSUE THREAD

**Issue by hayschan** [nopnop2002/esp-idf-mpu6050-dmp#3]
Hi there,

I hope this message finds you well. I'm relatively new to using the MPU6050 and MPU9250 series and have been exploring the capabilities of these sensors, particularly their integrated Digital Motion Processor (DMP). It’s clear that the DMP offloads significant processing from the host processor, which is fantastic for power-saving and efficiency.

> The embedded Digital Motion Processor (DMP) is located within the MPU-9250 and offloads computation of 
motion processing algorithms from the host processor. The DMP acquires data from accelerometers, gyroscopes, magnetometers and additional 3rd party sensors, and processes the data.

According to the datasheet, the DMP can process data from the gyroscopes, accelerometers, and magnetometers, and fuse these to output comprehensive motion data. Currently, I'm interested in implementing the MPU9250 with its DMP functionality but have noticed the example code is provided only for the MPU6050.

Could you possibly guide me on how to adjust the existing MPU6050_DMP code to work with the MPU9250? Any pointers, example codes, or resources you could share would be greatly appreciated.

Thank you for your time and for all the effort you put into maintaining this repository. I really like your implementation of the 3D object shown in the webpage. ❤️ 

Looking forward to your insights!

Best regards,

Hays Chan

**Comment by nopnop2002** [comment]
DMP also works on MPU9250.
MPU9250 is MPU6XXX+AK8963.

**Comment by hayschan** [comment]
Thanks for the reply. I will then use the [MPU6050_DMP6 example](https://github.com/nopnop2002/esp-idf-mpu6050-dmp/tree/main/MPU6050_DMP6) for the MPU9250. 

Do I have to configure any extra things for the MPU9250?

**Comment by nopnop2002** [comment]
>Do I have to configure any extra things for the MPU9250?


You don't need anything.

**Comment by hayschan** [comment]
Thanks for the clarification. 💘
